# .github/workflows/auto-merge-on-label.yml
name: Auto Merge PRs with 'merge' Label (by jaspermayone)

on:
  pull_request:
    types:
      - labeled

jobs:
  auto-merge:
    if: |
      github.event.label.name == 'merge' &&
      github.actor == 'jaspermayone'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Merge PR
        uses: pascalgn/automerge-action@v0.16.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MERGE_LABELS: merge
          MERGE_METHOD: squash
          MERGE_COMMIT_MESSAGE: pull-request-title
